### ISSUE TITLE
Fatal error: cannot read property ‘active’ of ‘undefined’

### ISSUE THREAD

**Issue by mbac** [SeydX/homebridge-camera-ui#16]
Hi,

I installed `homebridge-yi-camera` and ran into the missing `form-data` module bug, which I solved by manually installing it.

On the next run, however, I got the following error:

```
[10/13/2019, 9:14:23 PM] [YiCamera] Initializing YiCamera platform...
[10/13/2019, 9:14:23 PM] TypeError: Cannot read property 'active' of undefined
    at new YiCamera (/usr/lib/node_modules/homebridge-yi-camera/src/platform.js:39:34)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11
[10/13/2019, 9:14:24 PM] Got SIGTERM, shutting down Homebridge...
```

`config.json` Is parsing alright on JSON Lint, and the only things I changed were the names and IPs of the 2 cameras I’ve included.

Can anyone help?

**Comment by camrun91** [comment]
I am having this problem as well looks to be coming from line 39 in src/platform.js I can possibly look into this this week.

**Comment by camrun91** [comment]
this issue is actually because this git it for the homebridge-camera-ui plugin and not the yi camera plug in. just change the plugin and it works.
