### ISSUE TITLE
Incompatible with every current version of node basically useless. Please update !

### ISSUE THREAD

**Issue by thorget** [SeydX/homebridge-camera-ui#17]
Please update script. Thanks in advance!

**Comment by lvdfrnt** [comment]
Same experience here.

**Comment by 1onar** [comment]
Same here. 
After adding Camera UI the Homebridge crashes until i remove it. Didnt even touched Json.
Tried to downgrade Node. Still dont work.

**Comment by montanaishome** [comment]
Same experience here.

**Comment by airart320** [comment]
[11/25/2019, 9:13:05 PM] Plugin /usr/lib/node_modules/homebridge-camera-ui requires Node version of ^8.9.1 which does not satisfy the current Node version of v11.15.0. You may need to upgrade your installation of Node.
[11/25/2019, 9:13:05 PM] Loaded plugin: homebridge-camera-ui
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'form-data'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)

**Comment by lvdfrnt** [comment]
I figured out the issue, form-data is actually a node.js component that also needs to be installed.

Fix form data
Go to homebridge-camera-ui dir: cd /usr/local/lib/node_modules/homebridge-camera-ui
Install form data there: npm install form-data --save (you may need to use sudo before this command in case it fails)

**Comment by airart320** [comment]
This has worked, thanks!

> I figured out the issue, form-data is actually a node.js component that also needs to be installed.
> 
> Fix form data
> Go to homebridge-camera-ui dir: cd /usr/local/lib/node_modules/homebridge-camera-ui
> Install form data there: npm install form-data --save (you may need to use sudo before this command in case it fails)

**Comment by donavanbecker** [comment]
```
Plugin /usr/local/lib/node_modules/homebridge-camera-ui requires Node version of ^8.9.1 which does not satisfy the current Node version of v12.16.1. You may need to upgrade your installation of Node.
[3/26/2020, 4:39:21 PM] Loaded plugin: homebridge-camera-ui
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'form-data'
Require stack:
- /usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js
- /usr/local/lib/node_modules/homebridge-camera-ui/src/platform.js
- /usr/local/lib/node_modules/homebridge-camera-ui/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js',
    '/usr/local/lib/node_modules/homebridge-camera-ui/src/platform.js',
    '/usr/local/lib/node_modules/homebridge-camera-ui/index.js',
    '/usr/local/lib/node_modules/homebridge/lib/plugin.js',
    '/usr/local/lib/node_modules/homebridge/lib/server.js',
    '/usr/local/lib/node_modules/homebridge/lib/cli.js',
    '/usr/local/lib/node_modules/homebridge/bin/homebridge'
  ]
}
```

**Comment by subasically** [comment]
This is still an issue today.

```
The plugin "homebridge-camera-ui" requires a Homebridge version of ^0.4.49 which does not satisfy the current Homebridge version of 1.0.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stablity problems running this plugin.
[5/14/2020, 13:50:36] Plugin /usr/local/lib/node_modules/homebridge-camera-ui requires Node version of ^8.9.1 which does not satisfy the current Node version of v12.16.3. You may need to upgrade your installation of Node.
```

**Comment by QHose** [comment]
Go to the terminal in homebridge ui, remove the package which you installed via the gui and run `sudo npm i -g form-data@latest`  and reboot

**Comment by SeydX** [comment]
v2.2 should fix this

**Comment by dotWee** [comment]
Just had this issue on starting up a fresh homebridge docker instance running on a raspberry pi (armv7).  


Fixed it by adding `npm install --save form-data bcrypt` to the `$HOMEBRIDGE_DATA/startup.sh` file.  
Another solution would be running `docker exec -it homebridge npm install --save form-data bcrypt`.
