### ISSUE TITLE
Issue with zoneminder camera

### ISSUE THREAD

**Issue by andre1210** [SeydX/homebridge-camera-ui#218]
I'm using homebridge-camera-ui a long time with my foscam 9805W directly configured without issue. I'm using motion detection with mqtt and telegram snapshot messaging. Currently only one camera is configured.
My environment is a raspberry pi 4B with all recent updates (buster, homebridge, and camera-ui - version 4.2.7)
Now I tried to configure homebridge-camera-ui to use my zoneminder instance as camera source, because the picture is faster available.

Behavior: In Apple Home app I can see the snapshot of the camera, but if the mqtt motion trigger signal comes, an error is thrown and the processing stopps.
I would expect that the snapshot is stored and the telegram message is send like my old configuration.

Configuration:
             {
                    "name": "Einfahrt ZM",
                    "videoConfig": {
                        "source": "-re -i http://pi4b-2.fritz.box:81/zm/cgi-bin/nph-zms?mode=jpeg&monitor=1&scale=100&maxfps=15&buffer=1000&user=xxxxx&pass=xxxxxxx",
                        "stillImageSource": "-i http://pi4b-2.fritz.box:81/zm/cgi-bin/nph-zms?mode=single&monitor=1&scale=100&maxfps=5&buffer=1000&user=xxxxx&pass=xxxxxxx",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "debug": true
                    },
                    "mqtt": {
                        "motionTopic": "homebridge/blau/reed",
                        "motionMessage": "auf",
                        "motionResetTopic": "homebridge/blau/reed",
                        "motionResetMessage": "zu"
                    }
                }

**Logs**
during startup:
[19.8.2021, 09:07:27] [CameraUI] [Plugin] Einfahrt ZM: Starting video stream: 1280x720, 15 fps, 802 kbps
[19.8.2021, 09:07:27] [CameraUI] [Plugin] Einfahrt ZM: [fatal] Option stimeout not found.
[19.8.2021, 09:07:27] [CameraUI] [Plugin] Einfahrt ZM: ffmpeg exited with code: 1 and signal: null (Error)
[19.8.2021, 09:07:27] [CameraUI] [Plugin] Einfahrt ZM: Stopped video stream.

motion trigger:
[19.8.2021, 09:08:07] [CameraUI] [Interface] Einfahrt ZM: An error occured during handling motion event
[19.8.2021, 09:08:07] [CameraUI] Error: Image Buffer is empty!
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-camera-ui/server/services/ffmpeg.service.js:86:29)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12)

I guess that is is an configuration issue, do you have an idea?

thank you
André

**Environment**
- Node.js Version: v14.17.5
- Homebridge Version: v1.3.4
- Camera UI Version: v4.2.7
- Operating System: raspian buster
- Browser: chrome (PC and ipad)

**Comment by andre1210** [comment]
Update:
I tested the same workaround than used in 
https://github.com/SeydX/homebridge-camera-ui/issues/187
>> I've removed that option from config.start.js in my setup and it streams now great.

For me this solves my problem too.

**Comment by andre1210** [comment]
The workaround does not work as expected. I get again the "Image Buffer is empty!" error on motion trigger

**Comment by SeydX** [comment]
> The workaround does not work as expected. I get again the "Image Buffer is empty!" error on motion trigger

Hey sry for the late reply, working currently on the HSV implementation.

The error message usually appears when, for example, ffmpeg cannot access the camera to take a snapshot during a movement. The buffer that should normally be full (if a snapshot could be taken correctly) then becomes empty and this error message appears.

If the error message appears very often, please restart the camera(s) once and then the plugin. And maybe check if "dead" ffmpeg processes are still running.
