### ISSUE TITLE
HSV branch failure: TypeError: Cannot read property 'KHZ_32' of undefined

### ISSUE THREAD

**Issue by nicholasrobinson** [SeydX/homebridge-camera-ui#251]
**Describe the bug**
```
[10/10/2021, 3:53:03 PM] TypeError: Cannot read property 'KHZ_32' of undefined
    at new Camera (/homebridge/node_modules/homebridge-camera-ui/plugin/accessories/camera.js:38:57)
    at CameraUI.setupAccessory (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:145:31)
    at CameraUI.didFinishLaunching (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:77:14)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)
```

**To Reproduce**
Configure camera with HSV enabled using `homebridge-camera-ui v4.3.0-beta.21 `

**Expected behavior**
No exception.

**Logs**
See above.

**Screenshots**
N/A

**Environment**
- Node.js Version: v14.15.4
- Homebridge Version: v1.3.5
- Camera UI Version: v4.3.0-beta.21
- Operating System: Homebridge Docker Container
- Browser: N/A

**Comment by SeydX** [comment]
The beta version (hsv branch) depends on these PRs

https://github.com/homebridge/homebridge/pull/2973
https://github.com/homebridge/HAP-NodeJS/pull/904

It will NOT work with the official homebridge release yet

**Comment by seydx** [comment]
v5 (beta) now also works with the official hb release
