### ISSUE TITLE
v4.3 beta 94 Error

### ISSUE THREAD

**Issue by randomranran** [seydx/homebridge-camera-ui#277]
**Describe the bug**
v4.3 beta Error

**To Reproduce**
installed 4.3 beta and I receive the following error 

[11/4/2021, 3:32:46 PM] TypeError: Cannot read properties of undefined (reading 'KHZ_32')
    at new Camera (/homebridge/node_modules/homebridge-camera-ui/plugin/accessories/camera.js:42:57)
    at CameraUI.setupAccessory (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:158:29)
    at CameraUI.configure (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:85:14)
    at CameraUI.init (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:73:10)
    at HomebridgeAPI.emit (node:events:402:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)

**Expected behavior**

installed 4.3 beta and I receive the following error 

[11/4/2021, 3:32:46 PM] TypeError: Cannot read properties of undefined (reading 'KHZ_32')
    at new Camera (/homebridge/node_modules/homebridge-camera-ui/plugin/accessories/camera.js:42:57)
    at CameraUI.setupAccessory (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:158:29)
    at CameraUI.configure (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:85:14)
    at CameraUI.init (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:73:10)
    at HomebridgeAPI.emit (node:events:402:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)

**Logs**

[11/4/2021, 3:32:46 PM] TypeError: Cannot read properties of undefined (reading 'KHZ_32')
    at new Camera (/homebridge/node_modules/homebridge-camera-ui/plugin/accessories/camera.js:42:57)
    at CameraUI.setupAccessory (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:158:29)
    at CameraUI.configure (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:85:14)
    at CameraUI.init (/homebridge/node_modules/homebridge-camera-ui/plugin/index.js:73:10)
    at HomebridgeAPI.emit (node:events:402:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)

**Screenshots**
n/a

**Environment**
- Node.js Version: v16.13.0
- Homebridge Version: v3.12.8
- Camera UI Version: v4.3 beta 94
- Operating System: linux
- Browser: safari/chrome/ie

**Comment by seydx** [comment]
Hey

as described here #251 , the beta/alpha branch is NOT compatible with the current homebridge version

The beta/aloha version needs HSV and this is not implemented yet into homebridge, you need to wait to test the beta/alpha branch

**Comment by seydx** [comment]
v5.0.0-beta.40 can also be used without HSV
