### ISSUE TITLE
Homebridge crashes constantly when config is not fully populated

### ISSUE THREAD

**Issue by codyc1515** [seydx/homebridge-camera-ui#383]
**Describe the bug**
Homebridge crashes constantly and restarts over & over. It seems like the logger component is not loaded at the point that it throws the logger error, which cause the entire Homebridge to crash.

**To Reproduce**
Put the camera source without the `-I` flag.

**Expected behavior**
Should gracefully handle the error.

**Logs**
```
[18/01/2022, 21:04:25] TypeError: logger.warn is not a function
    at /usr/local/lib/node_modules/homebridge-camera-ui/services/config/config.service.js:154:18
    at Array.map (<anonymous>)
    at ConfigSetup._cameras (/usr/local/lib/node_modules/homebridge-camera-ui/services/config/config.service.js:150:8)
    at new ConfigSetup (/usr/local/lib/node_modules/homebridge-camera-ui/services/config/config.service.js:12:25)
    at new HomebridgeCameraUI (/usr/local/lib/node_modules/homebridge-camera-ui/src/platform.js:55:19)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
```

```
if (!sourceArguments.includes('-i')) {
  logger.warn('The source for this camera is missing "-i", it is likely misconfigured.', camera.name);
  camera.videoConfig.source = false;
}
```

**Comment by seydx** [comment]
Hey @codyc1515 

its fixed in the current beta version, can you try it pls

v5.0.11-beta.0

**Comment by seydx** [comment]
fixed in v5.0.11
