### ISSUE TITLE
No camera issue seen and error in logs.

### ISSUE THREAD

**Issue by aptonline** [SeydX/homebridge-camera-ui#4]
I have installed latest oznu Homebridge package on my Synology but after setting up I'm receiving the following errors in the logs:

```
[INFO] Start streaming video from Outside with 1280x720@299kBit
[6/17/2019, 10:20:12 PM] [CameraUI] [ERROR] Outside: An error occurs while making stream request
[6/17/2019, 10:20:12 PM] [CameraUI] [ERROR] Outside: FFmpeg exited with code -2
```

I can add the cameras fine in Home app but see no preview or output when clicking in the camera.

**Comment by SeydX** [comment]
set debug to true and post zour config pls

**Comment by aptonline** [comment]
Ok seeing the following in the logs:

```
2019-06-17T21:39:43.460Z CameraUI Downstairs: Closed with code -2
[6/17/2019, 10:39:43 PM] [CameraUI] [INFO] Outside: Snapshot from Outside at 480x270
2019-06-17T21:39:43.468Z CameraUI Outside: ffmpeg -rtsp_transport tcp -re -i rtsp://192.168.1.70/ch0_0.h264 -t 1 -s 480x270 -f image2 -
[6/17/2019, 10:39:43 PM] [CameraUI] [ERROR] Outside: An error occurs while making snapshot request
2019-06-17T21:39:43.469Z CameraUI Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-06-17T21:39:43.474Z CameraUI Outside: Closed with code -2
[6/17/2019, 10:39:59 PM] [CameraUI] [INFO] Outside: Snapshot from Outside at 480x270
2019-06-17T21:39:59.749Z CameraUI Outside: ffmpeg -rtsp_transport tcp -re -i rtsp://192.168.1.70/ch0_0.h264 -t 1 -s 480x270 -f image2 -
[6/17/2019, 10:39:59 PM] [CameraUI] [ERROR] Outside: An error occurs while making snapshot request
2019-06-17T21:39:59.750Z CameraUI Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by aptonline** [comment]
Sorry I've just seen this:

```
Homebridge Docker:

Add FFmpeg to packages

PACKAGES=ffmpeg
```

Where do I add `PACKAGES=ffmpeg`?

**Comment by SeydX** [comment]
i think in the settings (i dont using config-ui-x)

see hier

https://github.com/oznu/homebridge-config-ui-x/blob/afa747230636109dd21194493781523487fed3ba/ui/src/i18n/en.json#L73
