### ISSUE TITLE
Doorbell MQTT settings not availible in UI

### ISSUE THREAD

**Issue by r-sherwood** [seydx/homebridge-camera-ui#439]
**Describe the bug**
The settings to setup the doorbell MQTT topics are not available in the UI settings page.

**To Reproduce**
Try to setup MQTT settings for doorbell actions.

**Expected behavior**
Like MQTT motion should be a dialog to setup MQTT doorbell (see previous camera-ui versions)

**Screenshots**
![Screenshot 2022-02-03 at 16 03 17](https://user-images.githubusercontent.com/1226390/152368884-f7c3105f-4879-497d-a2fd-54d19fce63ed.png)

![Screenshot 2022-02-03 at 16 04 40](https://user-images.githubusercontent.com/1226390/152369433-45410bbd-66f8-4dcf-bd64-5d40a496eb30.png)

**Environment**
- Node.js Version: v14.19.0
- Homebridge Version: v1.4
- Camera UI Version: v5.0.16
- Operating System: raspbian buster
- Browser: FF

**Comment by r-sherwood** [comment]
Bum

**Comment by seydx** [comment]
should be fixed in v5.0.17-beta.1

**Comment by r-sherwood** [comment]
The update to v5.0.17-beta.1 completely crash the app.


```

[11/04/2022, 11:14:55] Error: spawn /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[11/04/2022, 11:14:55] Error: spawn /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[11/04/2022, 11:14:55] Got SIGTERM, shutting down Homebridge...
[11/04/2022, 11:15:00] [CameraUI] ESP32-Cam-Stairwell: Can not determine stream codecs, probe timed out
[11/04/2022, 11:15:00] [CameraUI] ESP32-Cam-Passage: Can not determine stream codecs, probe timed out
```

**Comment by seydx** [comment]
> The update to v5.0.17-beta.1 completely crash the app.
> 
> ```
> 
> [11/04/2022, 11:14:55] Error: spawn /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21)
> [11/04/2022, 11:14:55] Error: spawn /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21)
> [11/04/2022, 11:14:55] Got SIGTERM, shutting down Homebridge...
> [11/04/2022, 11:15:00] [CameraUI] ESP32-Cam-Stairwell: Can not determine stream codecs, probe timed out
> [11/04/2022, 11:15:00] [CameraUI] ESP32-Cam-Passage: Can not determine stream codecs, probe timed out
> ```

install as follow

`sudo npm i -g homebridge-camera-ui@5.0.17-beta.1 --unsafe-perm`
