### ISSUE TITLE
TypeError in camera.js "Cannot read properties of null"

### ISSUE THREAD

**Issue by dcabri** [seydx/homebridge-camera-ui#673]
**Describe the bug**
Updating rpm, brew modules and node to last versions
npm 8.19.2
brew Homebrew 3.6.10
node v19.0.1
macOS 13.0.1 (22A400)

The result is that the camera's are unavailable.

Launching package results in:

[11/10/2022, 9:28:19 AM] TypeError: Cannot read properties of null (reading 'get')
    at file:///usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:280:57
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

line in question resulting in error is in file
/usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js :

const controller = this.cameraUi.cameraController.get(this.accessory.displayName);

**To Reproduce**
Launch Homebridge with these versions of the software packages.

**Expected behavior**
Not seen this error before, camera's working.

**Logs**
[11/10/2022, 9:28:19 AM] TypeError: Cannot read properties of null (reading 'get')
    at file:///usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:280:57
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/10/2022, 9:28:19 AM] TypeError: Cannot read properties of null (reading 'get')
    at file:///usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:280:57
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/10/2022, 9:28:19 AM] TypeError: Cannot read properties of null (reading 'get')
    at file:///usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:280:57
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/10/2022, 9:28:19 AM] TypeError: Cannot read properties of null (reading 'get')
    at file:///usr/local/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:280:57
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/10/2022, 9:28:19 AM] Got SIGTERM, shutting down Homebridge...
[XXXXXX 7F38] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[XXXXXX 854A] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[XXXXXX D649] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[XXXXXX C3CD] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.

**Screenshots**
n/a

**Environment**
- Node.js Version: v19.0.1
- Homebridge Version: v3.6.10
- Camera UI Version: v5.0.27
- Operating System: macOS 13.0.1 (22A400)
- Browser: n/a

**Comment by dcabri** [comment]
I deleted in Home app all the camera's all the camera's, then launched this module again.
Now no more errors, but the camera's are not showing in Homebrige.
Analysing further...

**Comment by dcabri** [comment]
Changed Bridge port number to something else, changed Bridge Mac address to something else.
Now, all works fine again. Closing ticket.
