### ISSUE TITLE
HOOBS - Got SIGTERM, shutting down Bridge..

### ISSUE THREAD

**Issue by motogon** [SeydX/homebridge-camera-ui#69]
**Describe the bug**

After installation of a plug-in 
HOOBS - Got SIGTERM, shutting down Bridge... 

The problem appears when updating the web gui.

Config : 

{
            "platform": "CameraUI",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ui"
            },
            "name": "CameraUI",
            "auth": "form",
            "theme": "auto",
            "language": "Auto",
            "debug": true,
            "reset": false,
            "mqtt": {
                "active": true,
                "host": "192.168.1.74",
                "port": 1883,
                "username": "mqtt",
                "topic": "homebridge/motion"
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Camera 1",
                    "videoConfig": {
                        "source": "-i rtsp://xxxxx:xxxxx@192.168.3.109:554/cam/realmonitor?channel=1&subtype=0",
                        "stillImageSource": "-i rtsp://xxxx:xxxxx@192.168.3.109:554/cam/realmonitor?channel=1&subtype=0",
                        "maxStreams": 2,
                        "motion": true,
                        "vcodec": "copy",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "socketPort": 8100,
                        "maxFPS": 30,
                        "debug": true
                    }
                }
            ],
            "options": {
                "videoProcessor": "ffmpeg",
                "interfaceName": "enp0s31f6"
            }
        }

**Logs**

12.12.2020, 14:29:17 Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)12.12.2020, 14:29:17 Got SIGTERM, shutting down Bridge...12.12.2020, 14:29:17 Catching error on dropMembership: {"errno":-99,"code":"EADDRNOTAVAIL","syscall":"dropMembership"}12.12.2020, 14:29:17 Catching error on dropMembership: {"errno":-99,"code":"EADDRNOTAVAIL","syscall":"dropMembership"}12.12.2020, 14:29:19 Catching error on dropMembership: {"errno":-99,"code":"EADDRNOTAVAIL","syscall":"dropMembership"}12.12.2020, 14:29:19 Catching error on dropMembership: {"errno":-99,"code":"EADDRNOTAVAIL","syscall":"dropMembership"}

**Screenshots**

**Environment**
- Node.js Version: 14.15.1
- Homebridge Version: HOOBS 3.3.1
- Camera UI Version: 3.1.5
- Operating System: Ubuntu 20.04.1 LTS
- Browser: Firefox 83

**Comment by motogon** [comment]
The problem was solved by reinstalling ffmpeg in os
