### ISSUE TITLE
osx-temperature-sensor fails to load due to expected version that does not exist

### ISSUE THREAD

**Issue by ulysseskan** [seydx/homebridge-camera-ui#718]
**Describe the bug**
When starting homebridge after running brew upgrade, I get the error: ```The module '/opt/homebrew/lib/node_modules/homebridge-camera-ui/node_modules/osx-temperature-sensor/build/Release/smc.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 111.```

If I'm reading this correctly, this means I need to upgrade osx-temperature-sensor to version 1.11.  But v1.11 doesn't exist at https://www.npmjs.com/package/osx-temperature-sensor - so I can't upgrade.

`npm rebuild osx-temperature-sensor --update-binary` succeeds but does not fix the above problem.

Do I need to downgrade Node.js to get this module to work again?

**To Reproduce**
brew upgrade [did not capture what brew upgraded on its last run, but it probably included Node.js]
hb-service install

**Expected behavior**
homebridge-camera-ui still working

**Logs**
[1/17/2023, 4:44:44 PM] Error: The module '/opt/homebrew/lib/node_modules/homebridge-camera-ui/node_modules/osx-temperature-sensor/build/Release/smc.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1325:18)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Function.Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.cpuTemperature (/opt/homebrew/lib/node_modules/homebridge-camera-ui/node_modules/osx-temperature-sensor/lib/index.js:49:15)
    at /opt/homebrew/lib/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/cpu.js:1206:28
    at processTicksAndRejections (node:internal/process/task_queues:77:11)

**Screenshots**
<img width="899" alt="osx-temperature-sensor-module-fails-to-load" src="https://user-images.githubusercontent.com/71786368/213058080-a102a264-c55e-450c-96f3-60e09c63e71b.png">

**Environment**
- Node.js Version: v19.4.0
- Homebridge Version: v4.50.2
- Camera UI Version: v5.0.27
- Operating System: macOS Ventura 13.1
- Browser: Safari 16.2

**Comment by ulysseskan** [comment]
I was able to workaround and resolve this problem by running the following commands:

```
cd /opt/homebrew/lib/node_modules/homebridge-camera-ui/node_modules
mv osx-temperature-sensor /tmp
npm install osx-temperature-sensor --save
```

**Comment by MathSux** [comment]
This issue has been bugging me, and your solution totally fixed the problem. Thank you for posting!!
