### ISSUE TITLE
unhandled error "err_IPC_Channel_Closed"

### ISSUE THREAD

**Issue by wjkie** [seydx/homebridge-camera-ui#736]
**Describe the bug**

been getting unhandled errors for Camera-UI

**To Reproduce**
Not sure

**Expected behavior**
did not expect error 
**Logs**
[homebridge-camera-ui] node:events:491
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:400:5)
    at target.send (node:internal/child_process:740:16)
    at UiServer.ready (/var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/@homebridge/plugin-ui-utils/dist/server.js:105:17)
    at new UiServer (file:///var/lib/homebridge/node_modules/homebridge-camera-ui/homebridge-ui/server.js:35:10)
    at file:///var/lib/homebridge/node_modules/homebridge-camera-ui/homebridge-ui/server.js:256:10
    at file:///var/lib/homebridge/node_modules/homebridge-camera-ui/homebridge-ui/server.js:257:3
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Emitted 'error' event on process instance at:
    at node:internal/child_process:744:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'

**Screenshots**

**Environment**
- Node.js Version: v 18.13.0
- Homebridge Version: v1.6.0
- Camera UI Version: v5.0.27
- Operating System: Debian GNU/Linux (11)
- Browser: Safari

**Comment by djaytek** [comment]
I am having the same issue and just came here to post it and found out yours.
