### ISSUE TITLE
camera-ui keeps crashing

### ISSUE THREAD

**Issue by rasarisi** [seydx/homebridge-camera-ui#918]
Maybe something is set wrong?  But the cameras work then reboot work then reboot etc.

[4/11/2024, 8:14:43 PM] [CameraUI] Driveway PTZ: Motion ON
/var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:107
  return res.toISOString().substring(0, 10) + ' ' + res.toISOString().substring(11, 19);
             ^
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at parseElapsedTime (/var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:107:14)
    at parseLine (/var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:572:31)
    at /var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:663:23
    at Array.forEach (<anonymous>)
    at parseProcesses (/var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:661:13)
    at /var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:736:30
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:337:12)
[4/11/2024, 8:15:09 PM] [CameraUI] Child bridge process ended
[4/11/2024, 8:15:09 PM] [CameraUI] Process Ended. Code: 1, Signal: null
[4/11/2024, 8:15:16 PM] [CameraUI] Restarting Process...

**Environment**
- This is running on a Raspberry Pi 5
- Node.js Version: v20.12.0
- Homebridge Version:  v1.7.0
- Camera UI Version: v5.0.27
- Operating System: Debian GNU/Linux Bookworm (12)
- Browser: XXX

**Comment by SlothCroissant** [comment]
+1, including details as my Homebridge/Camera UI/NodeJS etc versions differ, so issue persists across various scenarios:

```[7/22/2024, 5:40:44 PM] [CameraUI] Driveway: Snapshot requested: 640 x 360
[7/22/2024, 5:40:44 PM] [CameraUI] Driveway: Sending snapshot: 640x360 (cached)
[7/22/2024, 5:40:44 PM] [CameraUI] Driveway: Resize command: ffmpeg -i pipe: -frames:v 1 -filter:v scale='min(640,iw)':'min(360,ih)':force_original_aspect_ratio=decrease -f image2 -
/var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:107
  return res.toISOString().substring(0, 10) + ' ' + res.toISOString().substring(11, 19);
             ^
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at parseElapsedTime (/var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:107:14)
    at parseLine (/var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:572:31)
    at /var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:663:23
    at Array.forEach (<anonymous>)
    at parseProcesses (/var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:661:13)
    at /var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:736:30
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:337:12)
[7/22/2024, 5:40:44 PM] [CameraUI] Child bridge process ended
[7/22/2024, 5:40:44 PM] [CameraUI] Process Ended. Code: 1, Signal: null
[7/22/2024, 5:40:51 PM] [CameraUI] Restarting Process...
```

Env (Proxmox VM):
 
```ryanb@hass:~$ hostnamectl
 Virtualization: kvm
Operating System: Debian GNU/Linux 12 (bookworm)
Kernel: Linux 6.1.0-16-amd64
Architecture: x86-64
Hardware Vendor: QEMU
Hardware Model: Standard PC _Q35 + ICH9, 2009_
Firmware Version: rel-1.16.2-0-gea1b7a073390-prebuilt.qemu.org
```


Node.js Version: v20.11.0
Homebridge Version: 1.8.4
Camera.UI Version: 5.0.27

**Comment by mkz212** [comment]
# 🎉 A new version of camera.ui
A new version of camera.ui is currently under active development. An initial alpha/beta release and previews are coming soon. Stay tuned for exciting updates: https://github.com/seydx/camera.ui/issues/448 .

This version will no longer be developed / fixed. The new version contains many novelties and fixes (most important is for HKSV recording).

**Comment by mkz212** [comment]
I think that here problem is with old dependency : 'systeminformation'.
