### ISSUE TITLE
Mac OS Sonoma - failed to install

### ISSUE THREAD

**Issue by Kositch** [seydx/homebridge-camera-ui#965]
**Describe the bug**
Lots of errors during the install regarding the Python missing / Gyp. I have tried manually install Python 3.2.15, but then there was lots of other errors regarding the Python / Gyp - see logs below.

**To Reproduce**
Try install the plugin on latest Mac OS Sonoma on Apple Sillicon.

**Expected behavior**
Successfull installation of plugin on Mac OS.

**Logs**
```
[##################] | reify:@aws-crypto/sha256-js: http fetch GET 200 https://registr

> dtrace-provider@0.8.8 install

> node-gyp rebuild || node suppress-error.js

Traceback (most recent call last):crypto/sha256-js: http fetch GET 200 https://registr

File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>

import gyp # noqa: E402

^^^^^^^^^^

File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>

import gyp.input

File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>

from distutils.version import StrictVersion

ModuleNotFoundError: No module named 'distutils'

gyp ERR! configure error

gyp ERR! stack Error: `gyp` failed with exit code: 1

gyp ERR! stack at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)

gyp ERR! stack at ChildProcess.emit (node:events:514:28)

gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)

gyp ERR! System Darwin 23.0.0

gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/dtrace-provider

gyp ERR! node -v v20.9.0

gyp ERR! node-gyp -v v9.4.0

gyp ERR! not ok

[##################] / reify:@aws-crypto/sha256-js: http fetch GET 200 https://registr

> ffmpeg-for-homebridge@0.0.9 install

> node install.js

ffmpeg-for-homebridge: darwin arm64 is not supported, you will need to install/compile ffmpeg manually.

[##################] | reify:@aws-crypto/sha256-js: http fetch GET 200 https://registr

> osx-temperature-sensor@1.0.8 install

> node-gyp rebuild

Traceback (most recent call last):crypto/sha256-js: http fetch GET 200 https://registr

File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>

import gyp # noqa: E402

^^^^^^^^^^

File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>

import gyp.input

File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>

from distutils.version import StrictVersion

ModuleNotFoundError: No module named 'distutils'

gyp ERR! configure error

gyp ERR! stack Error: `gyp` failed with exit code: 1

gyp ERR! stack at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)

gyp ERR! stack at ChildProcess.emit (node:events:514:28)

gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)

gyp ERR! System Darwin 23.0.0

gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/osx-temperature-sensor

gyp ERR! node -v v20.9.0

gyp ERR! node-gyp -v v9.4.0

gyp ERR! not ok

> pixel-change@1.1.0 install

> node-gyp-build

Traceback (most recent call last):crypto/sha256-js: http fetch GET 200 https://registr

File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>

import gyp # noqa: E402

^^^^^^^^^^

File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>

import gyp.input

File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>

from distutils.version import StrictVersion

ModuleNotFoundError: No module named 'distutils'

gyp ERR! configure error

gyp ERR! stack Error: `gyp` failed with exit code: 1

gyp ERR! stack at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)

gyp ERR! stack at ChildProcess.emit (node:events:514:28)

gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)

gyp ERR! System Darwin 23.0.0

gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/pixel-change

gyp ERR! node -v v20.9.0

gyp ERR! node-gyp -v v9.4.0

gyp ERR! not ok

npm ERR! code 1

npm ERR! path /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/pixel-change

npm ERR! command failed

npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in: /Users/steveangeli/.npm/_logs/2023-11-03T19_09_52_847Z-debug-0.log

Operation failed. Please review log for details.
```

**Screenshots**
N/A

**Environment**
- Node.js Version: v20.9.0
- Homebridge Version: v1.8.4
- Camera UI Version: v5.0.27/28 beta
- Operating System: Mac OS Sonoma 14.6.1
- Browser: Safari

**Comment by mkz212** [comment]
> [!IMPORTANT]
> 🚀 New Version in Development 🚀
>
> A new version of camera.ui is currently under active development - in progress are advanced works on the alpha version (for a closed group of testers) and the public beta will be available soon.
>
> Stay tuned for exciting updates: 
> https://github.com/seydx/camera.ui/issues/448

> [!CAUTION]
> This version will not be developed, current bugs will not be fixed and new features will not be introduced.

**Comment by Kositch** [comment]
I hope that this New Version will be possible to install on Mac without any issues...
