### ISSUE TITLE
plugin installation is not done - Error: ENOSPC: no space left on dev - QNAP

### ISSUE THREAD

**Issue by jaranor** [seydx/homebridge-camera-ui#973]
**Describe the bug**
plugin installation is not done, 
I have plenty of space and it does not install the plugin, other plugins have been installed correctly, but this one does not install.

**To Reproduce**
install

**Expected behavior**
correct installation

**Logs**
USER: root
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-camera-ui@5.0.28-beta.0

[##################] - reify:es-abstract: sill tar Error: ENOSPC: no space left on dev
> dtrace-provider@0.8.8 install
> node-gyp rebuild

gyp ERR! configure error ify:es-abstract: sill tar Error: ENOSPC: no space left on dev
gyp ERR! stack Error: ENOSPC: no space left on device, write
gyp ERR! System Linux 5.10.60-qnap
gyp ERR! command "/opt/homebridge/bin/node" "/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /homebridge/node_modules/homebridge-camera-ui/node_modules/dtrace-provider
gyp ERR! node -v v18.13.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 

> pixel-change@1.1.0 install
> node-gyp-build

gyp ERR! configure error ify:es-abstract: sill tar Error: ENOSPC: no space left on dev
gyp ERR! stack Error: ENOSPC: no space left on device, write
gyp ERR! System Linux 5.10.60-qnap
gyp ERR! command "/opt/homebridge/bin/node" "/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /homebridge/node_modules/homebridge-camera-ui/node_modules/pixel-change
gyp ERR! node -v v18.13.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /homebridge/node_modules/homebridge-camera-ui/node_modules/pixel-change
npm ERR! command failed
npm ERR! command sh -c -- node-gyp-build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2024-10-25T23_51_09_750Z-debug-0.log

Error: Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

**Environment**
- Node.js Version: v18.13.0
- Homebridge Version: v1.8.4
- Camera UI Version: v5.0.27 / 5.028 beta
- Operating System: Qnap Linux
- Browser: Chrome en windows

![Captura de pantalla 2024-10-26 020950](https://github.com/user-attachments/assets/5a9525e7-930e-4602-8549-d4e95cfd9774)

**Comment by jaranor** [comment]
![Captura de pantalla 2024-10-26 132032](https://github.com/user-attachments/assets/c6d0976c-bbe0-4531-a63d-79887e2e76d3)

**Comment by jaranor** [comment]
![Captura de pantalla 2024-10-26 132339](https://github.com/user-attachments/assets/382d5e4e-cf0a-4e2b-aad3-77290dde980d)

**Comment by jaranor** [comment]
he instalado node.js version 20 y continua igual.

Bundled install / update could not complete. Trying regular install / update using npm.

USER: root
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-camera-ui@5.0.27


> dtrace-provider@0.8.8 install
> node-gyp rebuild || node suppress-error.js


gyp ERR! configure error 
gyp ERR! stack Error: ENOSPC: no space left on device, write
gyp ERR! stack at async write (node:internal/fs/promises:742:8)
gyp ERR! stack at async writeFileHandle (node:internal/fs/promises:499:7)
gyp ERR! stack at async createConfigGypi (/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/lib/create-config-gypi.js:141:3)
gyp ERR! stack at async createConfigFile (/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:104:24)
gyp ERR! stack at async run (/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 5.10.60-qnap
gyp ERR! command "/opt/homebridge/bin/node" "/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /homebridge/node_modules/homebridge-camera-ui/node_modules/dtrace-provider
gyp ERR! node -v v20.18.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok 
node:internal/modules/package_json_reader:93
        throw error;
        ^

SyntaxError: Error parsing /homebridge/node_modules/homebridge-camera-ui/node_modules/dtrace-provider/package.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at read (node:internal/modules/package_json_reader:80:16)
    at readPackage (node:internal/modules/package_json_reader:141:10)
    at readPackageScope (node:internal/modules/package_json_reader:164:19)
    at shouldUseESMLoader (node:internal/modules/run_main:81:15)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:161:24)
    at node:internal/main/run_main_module:28:49 {
  path: '/homebridge/node_modules/homebridge-camera-ui/node_modules/dtrace-provider/package.json'
}

Node.js v20.18.0

> ffmpeg-for-homebridge@0.0.9 install
> node install.js

node:internal/modules/package_json_reader:93
        throw error;
        ^

SyntaxError: Error parsing /homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/package.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at read (node:internal/modules/package_json_reader:80:16)
    at readPackage (node:internal/modules/package_json_reader:141:10)
    at readPackageScope (node:internal/modules/package_json_reader:164:19)
    at shouldUseESMLoader (node:internal/modules/run_main:81:15)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:161:24)
    at node:internal/main/run_main_module:28:49 {
  path: '/homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/package.json'
}

Node.js v20.18.0
npm error code 1
npm error path /homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge
npm error command failed
npm error command sh -c node install.js
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-10-26T12_54_41_873Z-debug-0.log

Error: Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

**Comment by jaranor** [comment]
Realizando la instalacion por terminal arroja este error.

![Captura de pantalla 2024-10-26 150241](https://github.com/user-attachments/assets/215504d1-ac13-4a48-b567-1aa4a33384dc)
